services:
  postgres:
    image: postgres:15
    container_name: wealthwise_postgres
    environment:
      POSTGRES_DB: wealthwise
      POSTGRES_USER: wealthuser
      POSTGRES_PASSWORD: wealthpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: wealthwise_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
